---

- hosts: itrust

  gather_facts: no

  vars_prompt:
  - name: "gitUsername"
    prompt: "Enter Unity Id"
    private: no
  - name: "gitPassword"
    prompt: "Enter your password"
    private: yes
  tasks:

  - name: Step 1 install maven
    apt: pkg=maven update_cache=yes
    become: yes
  - name: Step 2 install git
    apt: name=git state=present
    become: yes
  - name: Step 3 set oracle java repo
    apt_repository: repo='ppa:webupd8team/java' state=present
    become: yes
#  - name: Step 4 Update Anyway
#    shell: sudo apt-get update
#    become: yes
  - name: Step 5 Java license
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
    become: yes
  - name: Step 6 Install Oracle Java 8
    apt: name={{item}} state=latest
    with_items:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default
    become: yes
  - name: Step 7 check if public repo already cloned
    stat:
      path: /home/vagrant/iTrust2-v2
    register: result
  - name: Step 8 clone iTrust repo
    git: repo=https://{{ gitUsername }}:{{ gitPassword }}@github.ncsu.edu/engr-csc326-staff/iTrust-v23.git dest=/home/{{ ansible_ssh_user }}/
    become: yes
    when: result.stat.isdir is not defined
  - name: Step 9 set MySQL root password
    debconf: name='mysql-server' question='mysql-server/root_password' value='root' vtype='password'
    become: yes
  - name: Step 10 confirm MySQL root password
    debconf: name='mysql-server' question='mysql-server/root_password_again' value='root' vtype='password'
    become: yes
  - name: Step 11 install mysql server
    apt: name=mysql-server state=present
    become: yes
  - name: Step 12 check if db.properties file already exists
    stat:
      path: /home/vagrant/iTrust2-v2/iTrust2/src/main/java/db.properties
    register: result
  - name: Step 13 copy the contents of db.properties.template file
    command: mv db.properties.template db.properties
    args:
      chdir: "/home/vagrant/iTrust2-v2/iTrust2/src/main/java"
    when: result.stat.isdir is not defined
  - name: Step 14 check if email.properties file already exists
    stat:
      path: /home/vagrant/iTrust2-v2/iTrust2/src/main/java/email.properties
    register: result
  - name: Step 15 copy the contents of email.properties.template file
    command: mv email.properties.template email.properties
    args:
      chdir: "/home/vagrant/iTrust2-v2/iTrust2/src/main/java"
    when: result.stat.isdir is not defined
  - name: Step 16 check if hibernate.properties file already exists
    stat:
      path: /home/vagrant/iTrust2-v2/iTrust2/src/main/resources/hibernate.properties
    register: result
  - name: Step 17 copy the contents of hibernate.properties.template file
    command: mv hibernate.properties.template hibernate.properties
    args:
      chdir: "/home/vagrant/iTrust2-v2/iTrust2/src/main/resources"
    when: result.stat.isdir is not defined
  - name: Step 18 Change password in hibernate.properties file
    lineinfile:
      path: /home/vagrant/iTrust2-v2/iTrust2/src/main/resources/hibernate.properties
      regexp: '^hibernate.connection.password = '
      line: 'hibernate.connection.password = root'
  - name: Step 19 Change password in db.properties file
    lineinfile:
      path: /home/vagrant/iTrust2-v2/iTrust2/src/main/java/db.properties
      regexp: '^password '
      line: 'password root'
  - name: Step 20 restart MySQL
    service: name=mysql state=restarted
    become: yes
  - name: Step 21 run test to verify iTrust Build
    shell: sudo mvn clean test verify checkstyle:checkstyle
    args:
      chdir: "/home/vagrant/iTrust2-v2/iTrust2/"
    become: yes