---
- hosts: jenkins-tester

  gather_facts: no

  become: yes

  tasks:

    - name: Install Git, Java JDK, Nodejs, NPM, Maven
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
      - "git"
      - "default-jdk"
      - "nodejs"
      - "npm"
      - "maven"

    - name: Get Jenkins key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key

    - name: Add Jenkins repo
      apt_repository:
        repo: "deb http://pkg.jenkins.io/debian-stable binary/"

    - name: Install Jenkins
      apt:
        name: jenkins
        update_cache: yes

    - name: Disable Jenkins setup wizard
      lineinfile:
        dest: /etc/default/jenkins
        regexp: '^JAVA_ARGS='
        line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'

    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted

    - name: Create init.groovy.d directory
      file:
        path: /var/lib/jenkins/init.groovy.d
        state: directory
        mode: 0755

    - name: Copy configure default Jenkins users script
      template:
        src: configure-users.groovy
        dest: /var/lib/jenkins/init.groovy.d/configure-users.groovy
        owner: jenkins
        group: jenkins
        mode: 0755

    - name: Copy retrieve Jenkins user token script
      template:
        src: retrieve-token.groovy
        dest: /var/lib/jenkins/init.groovy.d/retrieve-token.groovy
        owner: jenkins
        group: jenkins
        mode: 0755

    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted

    - name: Wait for Jenkins to start up before proceeding
      shell: "curl -D - --silent --max-time 5 http://{{ jenkins_ip_address }}:8080/cli/"
      register: result
      until: (result.stdout.find("403 Forbidden") != -1) or (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
      retries: 60
      delay: 5
      changed_when: false
      check_mode: no

    - name: Retreive token
      shell: "grep JENKINS_TOKEN /var/log/jenkins/jenkins.log"
      register: jenkins_token
